[colors.primary]
background = '#1a1111'
foreground = '#f1dedd'

[colors.selection]
text = '#f1dedd'
background = '#733331'

[colors.cursor]
text = '#1a1111'
cursor = '#ffb3ae'

[colors.normal]
black   = '#1a1111'
red     = '#ff7372'
green   = '#9aff7f'
yellow  = '#ffe472'
blue    = '#f29b95'
magenta = '#763531'
cyan    = '#ffb3ae'
white   = '#fff0ef'

[colors.bright]
black   = '#a59a99'
red     = '#ffa09f'
green   = '#b8ffa5'
yellow  = '#ffeda5'
blue    = '#ffbeba'
magenta = '#ffc9c6'
cyan    = '#ffdcda'
white   = '#fff8f8'
