[colors.primary]
background = '#13121c'
foreground = '#e4e0ef'

[colors.selection]
text = '#e4e0ef'
background = '#3100e4'

[colors.cursor]
text = '#13121c'
cursor = '#c4c0ff'

[colors.normal]
black   = '#13121c'
red     = '#ff7293'
green   = '#7fff97'
yellow  = '#ffd872'
blue    = '#aeaaf2'
magenta = '#434076'
cyan    = '#c4c0ff'
white   = '#f0efff'

[colors.bright]
black   = '#9a99a5'
red     = '#ff9fb5'
green   = '#a5ffb6'
yellow  = '#ffe6a5'
blue    = '#ccc9ff'
magenta = '#d5d2ff'
cyan    = '#e4e2ff'
white   = '#f8f8ff'
