cursor #f1dedd
cursor_text_color #d8c2c0

foreground            #f1dedd
background            #1a1111
selection_foreground  #442928
selection_background  #e7bdb9
url_color             #ffb3ae

color0   #1a1111
color1   #ff7372
color2   #9aff7f
color3   #ffe472
color4   #f29b95
color5   #763531
color6   #ffb3ae
color7   #fff0ef
color8   #a59a99
color9   #ffa09f
color10  #b8ffa5
color11  #ffeda5
color12  #ffbeba
color13  #ffc9c6
color14  #ffdcda
color15  #fff8f8
